server:
  port: 8090

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:20001/eureka/

spring:
  application:
    name: E-A02
  profiles:
    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
    active: dev
  redis:
    host: 127.0.0.1
    password:
    port: 6379



  #数据库连接信息
  datasource:
    name: test
#    url: jdbc:mysql://127.0.0.1:3306/gxinvoice?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true
#    username: guoxin
#    password: sc0j8i5K
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/fin-tax?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://127.0.0.1:3306/fin-tax?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true
#    username: root
#    password: 123456
    #    url: jdbc:oracle:thin:@106.15.205.224:1521:orcl
    #    username: hundwe_invoice
    #    password: hundwe_invoice
    #    url: jdbc:oracle:thin:@localhost:1521:orcl
    #    username: system
    #    password: 123456
    #    url: jdbc:sqlserver://localhost:1433;DatabaseName=zhys_zjsh
    #    username: sa
    #    password: Jinshui123
    #    url: jdbc:sqlserver://localhost:1433;DatabaseName=zhys_zjsh
    #    username: sa
    #    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    #    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-request-size: 10MB
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8


mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    default-executor-type: simple
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  executor-type: simple



eureka:
  instance:
    prefer-ip-address: true
  client: 
    service-url:
      defaultZone: http://localhost:20002/eureka/
# 分页配置
pagehelper:
  helper-dialect: mysql
  #helper-dialect: sqlserver
  reasonable: false
  support-methods-arguments: true
  params: count=countSql


#日志
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    com.example.demo.mapper: debug


code:
  controller: com.zhys.controller

#MB
multipart:
  maxFileSize: 10
  maxRequestSize: 50


zhys:
  appId: 91330105MA2B0AD277
